-- V1: six-entity schema. Room, Resident, Contact, Complaint,
-- ComplaintStatusHistory, StaffUser. No vendor-specific SQL here.

CREATE TABLE room (
    room_number VARCHAR(16)  PRIMARY KEY,
    block       VARCHAR(32)  NOT NULL,
    floor       INTEGER      NOT NULL,
    occupants   VARCHAR(512)
);

CREATE TABLE resident (
    roll_number VARCHAR(16) PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    room_number VARCHAR(16),
    contact     VARCHAR(64),
    CONSTRAINT fk_resident_room FOREIGN KEY (room_number) REFERENCES room (room_number)
);

CREATE TABLE contact (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role          VARCHAR(64)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    phone         VARCHAR(32),
    email         VARCHAR(128),
    display_order INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE complaint (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_name VARCHAR(128)  NOT NULL,
    room_number    VARCHAR(16)   NOT NULL,
    category       VARCHAR(32)   NOT NULL,
    description    VARCHAR(2000) NOT NULL,
    status         VARCHAR(32)   NOT NULL,
    priority       INTEGER       NOT NULL DEFAULT 0,
    client_token   VARCHAR(64)   UNIQUE,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE complaint_status_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT      NOT NULL,
    old_status   VARCHAR(32),
    new_status   VARCHAR(32) NOT NULL,
    changed_by   VARCHAR(64) NOT NULL,
    changed_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_history_complaint FOREIGN KEY (complaint_id) REFERENCES complaint (id)
);

CREATE INDEX idx_complaint_status_created ON complaint (status, created_at);
CREATE INDEX idx_history_complaint       ON complaint_status_history (complaint_id, changed_at);

CREATE TABLE staff_user (
    username      VARCHAR(64)  PRIMARY KEY,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    display_name  VARCHAR(128)
);